### ISSUE TITLE
Provide graphviz + Dependencies

### ISSUE THREAD

**Issue by escar42** [cloudfoundry/cflinuxfs3#10]
Please consider adding the graphviz package plus its dependencies to the stack. https://packages.ubuntu.com/bionic/graphviz

It would be nice to have it, so PlantUML can be executed in Cloud Foundry.
We´ve done this with cflinuxfs2, but cflinuxfs3 is missing several dependencies for graphwiz, so plantuml can not be used to its full potential.

**Comment by sclevine** [comment]
Sorry for the delay @escar42, we're planning to evaluate the impact of adding graphviz soon.

**Comment by kardolus** [comment]
@escar42 We created an investigative story regarding this issue; we will play that one first:

https://www.pivotaltracker.com/n/projects/1042066/stories/165449211

**Comment by zmackie** [comment]
This will be included when our next release is out. Should be 9/3 @slevine
