### ISSUE TITLE
Can we add gpg to fs3?

### ISSUE THREAD

**Issue by zmackie** [cloudfoundry/cflinuxfs3#17]
We had it in fs2, can we have it in fs3? See: https://github.com/cloudfoundry/cflinuxfs2/blob/master/cflinuxfs2/cflinuxfs2_receipt#L75

**Comment by adamwinn** [comment]
Any updates on this yet?

**Comment by zmackie** [comment]
Unfortunately not.

**Comment by martyspiewak** [comment]
This is included as part of the [Paketo full stack](https://github.com/paketo-buildpacks/full-release) build and run images for next generation Paketo buildpacks.

I'm closing this issue for now but let us know if it would still be useful in cflinuxfs3 and we'll take in under consideration.
