### ISSUE TITLE
Can you accept gettext-base?

### ISSUE THREAD

**Issue by yoshwata** [cloudfoundry/cflinuxfs3#20]
I'd like to use gettext-base package with my build environment.
https://manpages.debian.org/jessie-backports/gettext-base/index.html

Please kindly consider this matter.

**Comment by martyspiewak** [comment]
Sorry for the delay on this. Do you need this at runtime as well? We are evaluating whether it makes sense to add to the next generation Paketo build and run images.

Also, could you describe your use case for gettext-base?

**Comment by yoshwata** [comment]
Thank you for your reaction. I'm sorry, but I can't clearly remember why I needed gettext-base. I probably came up with another solution at that time. So this issue is closed. If I remember, please let me know again.
