### ISSUE TITLE
How do I know the version of this OS

### ISSUE THREAD

**Issue by saranshbansal** [cloudfoundry/cflinuxfs3#21]
How do I retrieve which version of cflinuxfs3 is used for an application deployed on pcf?

**Comment by mdelillo** [comment]
Hi @saranshbansal, sorry for the slow response. I don't know of a way to find the cflinuxfs3 version just by looking at the app.

But if you have access to the bosh manifest or deployment you can look at the version of the `cflinuxfs3-release` which will correspond to the version of cflinuxfs3. For example, the latest cf-deployment is using cflinuxfs3 0.215.0 [here](https://github.com/cloudfoundry/cf-deployment/blob/738ffe4540c50ca28b497cbd59ced1f6317a6b3a/cf-deployment.yml#L2698-L2701).
