### ISSUE TITLE
How to modify /etc/hosts file?

### ISSUE THREAD

**Issue by koosomang** [cloudfoundry/cflinuxfs3#22]
I want to add custom hosts.

Initially, a stack was created by adding a part to modify /etc/hosts in the Dockerfile RUN part. The added part is as follows.

----
RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale && \
  echo "$locales" | grep -f - /usr/share/i18n/SUPPORTED | cut -d " " -f 1 | xargs locale-gen && \
  dpkg-reconfigure -fnoninteractive -pcritical locales tzdata libc6 && \
  echo 'test' > /etc/test.txt && \
  echo '1.1.1.1   test.host.local' > /etc/hosts

---
However, when I checked the contents of cflinuxfs3.x86_64.tar.gz /etc/hosts after creation, it was not added.

**Comment by martyspiewak** [comment]
There does not seem to be a great way to do this in a Dockerfile.

There are some solutions you can try out [here](https://stackoverflow.com/questions/38302867/how-to-update-etc-hosts-file-in-docker-image-during-docker-build) but this problem does not seem specific to cflinuxfs3.
