### ISSUE TITLE
Ghostscript

### ISSUE THREAD

**Issue by beemnet20** [cloudfoundry/cflinuxfs3#23]
Hello,
I'm trying to run a django application on Cloud Foundry using cflinuxfs3 stack and python buildpack. I'm trying to parse PDFs using camelot-py (which is dependent on Ghostscript), however I get "RuntimeError: Please make sure that Ghostscript is installed" 

I saw [this post](https://github.com/cloudfoundry/cflinuxfs2/issues/40) tried the below method where I created a `bin` folder in the same folder as my manifest.yml and I placed `gs` in there but it didn't work I still get the same error. I would really appreciate any help I can get. 

Thank you! 

Suggestion from the post below

>     1. Download [Ghostscript for Linux x86 (64 bit)](https://ghostscript.com/download/gsdnld.html)
> 
>     2. Extract the binary
> 
>     3. Rename it to `gs`
> 
>     4. Add it to the folder `bin/` in your application
> 
>     5. Prepend the following part to you `command` in `manifest.yml`: `export PATH=$PATH:$PWD/bin/ && `

**Comment by martyspiewak** [comment]
Unfortunately we aren't too familiar with how this library works. If you ask in the [ruby-buildpack repo](https://github.com/cloudfoundry/ruby-buildpack) they may be able to help more than we can.
