### ISSUE TITLE
New CVEs should create Github issues instead of tracker stories

### ISSUE THREAD

**Issue by martyspiewak** [cloudfoundry/cflinuxfs3#24]
Right now there is a [pipeline](https://buildpacks.ci.cf-app.com/teams/core-deps/pipelines/notifications/jobs/categorize-security-notices-cflinuxfs3/builds/164) in Concourse that creates Tracker stories in a private backlog whenever a new USN is released affecting cflinuxfs3. These stories are auto-started and delivered by the pipeline when the USN has been patched. The configuration for this pipeline lives in [cloudfoundry/core-deps-ci](https://github.com/cloudfoundry/core-deps-ci/blob/main/pipelines/notifications.yml#L139-L158).

We should update this pipeline to open (and close?) issues in this repo to surface this information better.

**Comment by pburkholder** [comment]
This feature would be a great way for me to document to assessors that cflinuxfs3 is continually rebuilt to address CVEs. 👍

**Comment by ryanmoran** [comment]
@arjun024 is this something we are covering with our recent changes in automation?

**Comment by arjun024** [comment]
No.
I can't ever remember seeing tracker issues. The CVEs are documented in the public register here https://github.com/cloudfoundry/public-buildpacks-ci-robots/tree/main/new-cve-notifications

And, not sure we need issues for tasks auto-started and delivered by the pipeline.

cc @brayanhenao @sophiewigmore @robdimsdale

**Comment by sophiewigmore** [comment]
Agreed that I'm not sure if we necessarily need issues for CVEs if the tasks to patch them are completely automated

**Comment by ryanmoran** [comment]
Do we feel like the current public disclosure process, posting the USNs and their CVE details to the release notes, is sufficient to resolve this issue?

**Comment by robdimsdale** [comment]
> Do we feel like the current public disclosure process, posting the USNs and their CVE details to the release notes, is sufficient to resolve this issue?

Personally, yes.

@pburkholder - is there something about the current process that is lacking for you as a consumer of the stack?

**Comment by pburkholder** [comment]
https://github.com/cloudfoundry/public-buildpacks-ci-robots/tree/main/new-cve-notifications will suffice for our needs, thank you.

**Comment by ryanmoran** [comment]
Closing as resolved.
