### ISSUE TITLE
Include libpcre2-8-0 to stack

### ISSUE THREAD

**Issue by Bsting** [cloudfoundry/cflinuxfs3#29]
Would it be possible to include libpcre2-8-0 to the stack? We are facing issue when loading ngx_http_js_module with the latest nginx buildpack. From https://nginx.org/packages/ubuntu/dists/bionic/nginx/binary-amd64/Packages, dependent library libpcre for nginx-module-njs change from libpcre3 to libpcre2-8-0 from nginx 1.22.0 onwards

![image](https://user-images.githubusercontent.com/7638997/203237981-fc800924-a00e-464a-9fb4-1d46470341a4.png)

**Comment by ryanmoran** [comment]
Closing this in favor of the resolution outlined in https://github.com/cloudfoundry/nginx-buildpack/issues/168.
